### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by mshaek** [yiweilu3/Few-shot-Scene-adaptive-Anomaly-Detection#13]
Hi,

I am trying to implement this code but I am running into some issues. I am not able to find the right parameters used in main.py script. I am getting the following error when I run. 

Traceback (most recent call last):
  File "train.py", line 276, in <module>
    main(k_shots, num_tasks, adam_betas, gen_lr, dis_lr, total_epochs, model_folder_path)
  File "train.py", line 110, in main
    train_path_list = createEpochData(frame_path, num_tasks, k_shots)
  File "/content/drive/MyDrive/FSAAD/utils.py", line 46, in createEpochData
    video_folder, k_shot_frames = generate_k_shot_frames(video, k_shots)        
  File "/content/drive/MyDrive/FSAAD/utils.py", line 16, in generate_k_shot_frames
    all_frames = list(os.walk(video_folder))[0][2]
IndexError: list index out of range

I will be grateful if you can share the full code with me.

Thanks
Mahfuzur
Student, USM Malaysia

**Comment by yinyexingchen** [comment]
> Hi,
> 
> I am trying to implement this code but I am running into some issues. I am not able to find the right parameters used in main.py script. I am getting the following error when I run.
> 
> Traceback (most recent call last): File "train.py", line 276, in main(k_shots, num_tasks, adam_betas, gen_lr, dis_lr, total_epochs, model_folder_path) File "train.py", line 110, in main train_path_list = createEpochData(frame_path, num_tasks, k_shots) File "/content/drive/MyDrive/FSAAD/utils.py", line 46, in createEpochData video_folder, k_shot_frames = generate_k_shot_frames(video, k_shots) File "/content/drive/MyDrive/FSAAD/utils.py", line 16, in generate_k_shot_frames all_frames = list(os.walk(video_folder))[0][2] IndexError: list index out of range
> 
> I will be grateful if you can share the full code with me.
> 
> Thanks Mahfuzur Student, USM Malaysia

hello ,have  you solve this problem？I met the same question
