### ISSUE TITLE
Testing the trained models

### ISSUE THREAD

**Issue by AbdulMoqeet** [yiweilu3/Few-shot-Scene-adaptive-Anomaly-Detection#9]
Hello, 

Thank you for sharing the code. 

Once the network is trained using `train.py`, how to test the model? 

Regards,
AM

**Comment by carolchenyx** [comment]
@AbdulMoqeet Dear AbdulMoqeet, I would like to ask a question about train.py. When I ran it , this line of the code(
torch.autograd.grad(dis_validation_loss, discriminator.parameters())) will raise the error({RuntimeError}invalid gradient at index 0 - got [1] but expected shape compatible with [1, 1]). Do you know how to fix it? Thank you.

**Comment by AbdulMoqeet** [comment]
@carolchenyx I checked my code but couldn't get hint.  I was facing similar errors but don't remember how I fixed them though. 

Did you make any changes in the code? How's your data directory look like?

**Comment by carolchenyx** [comment]
@AbdulMoqeet I changed a little bit about the data process. The data directory is like (/media/hkuit104/24d4ed16-ee67-4121-8359-66a09cede5e7/AbnormalDetection/DATASET/SHT/testing/frames/).

**Comment by AbdulMoqeet** [comment]
It may be a problem of data loading.. My directory looks like `videos\frames\08\08_003 ` where `08 `is the Task number and '08_003' is video number. I am giving  'videos\frames' as an input.

**Comment by carolchenyx** [comment]
@AbdulMoqeet  Oh, I see. Let me try it first. Super thanks for you quick reply.

**Comment by carolchenyx** [comment]
@AbdulMoqeet Dear AM, it seems will raise the same problem. I pushed the code I used in (https://github.com/carolchenyx/Few-shot-Scene-adaptive-Anomaly-Detection). I will be very grateful if you can help to check it. Thank you. 
Traceback (most recent call last):
  File "/media/hkuit104/24d4ed16-ee67-4121-8359-66a09cede5e7/AbnormalDetection/Few-shot-Scene-adaptive-Anomaly-Detection/train.py", line 269, in <module>
    main(k_shots, num_tasks, adam_betas, gen_lr, dis_lr, total_epochs, model_folder_path)
  File "/media/hkuit104/24d4ed16-ee67-4121-8359-66a09cede5e7/AbnormalDetection/Few-shot-Scene-adaptive-Anomaly-Detection/train.py", line 199, in main
    gen_grads = torch.autograd.grad(gen_validation_loss, generator.parameters())
  File "/home/hkuit104/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/autograd/__init__.py", line 225, in grad
    inputs, allow_unused, accumulate_grad=False)
RuntimeError: invalid gradient at index 0 - got [1] but expected shape compatible with [1, 1]

**Comment by AbdulMoqeet** [comment]
@carolchenyx Added a pull request for working code. Changes are made in your code. Have fun!

**Comment by carolchenyx** [comment]
@AbdulMoqeet  Great! Super thanks again.

**Comment by abhishekaich27** [comment]
@AbdulMoqeet @carolchenyx Can you share the folder structure of training videos? I have extracted the frames under folder name of videos. Below is the structure I have. Is this correct?
```Shanghai-Tech
|- Training
    |-frames
         |- 01_001
         |- 01_002
         |- 01_003
```
This is the structure of the **training** videos (which by default in Shanghai-Tech, doesn't provide anomalies in training set.)

**Comment by AbdulMoqeet** [comment]
@abhishekaich27 Yes, but that default structure didn't work for me. I had to change the directories structure. 

My directory looks like \Training\frames\08\08_003\*.jpg where 08 is the Task number, '08_003' is video number and *.jpg represent the video frames.  

Let me know if the problem still persists.

**Comment by abhishekaich27** [comment]
Exactly @AbdulMoqeet. Does the _Task number_ has some relation with _Video number_? e.g. ```08``` of ```08_003```? These first two digits have some particular meaning?

**Comment by AbdulMoqeet** [comment]
Yes, all of the videos started from same numbers (e.g. `08` in `08_003`) should be in the same folder named as ` 08`. 

Those particular two digits refer to task/scene number.  

For Task 8:
` \Training\frames\08\08_001\*.jpg`
` \Training\frames\08\08_002\*.jpg`

For Task 7:
` \Training\frames\07\07_001\*.jpg`
` \Training\frames\07\07_002\*.jpg`

**Comment by abhishekaich27** [comment]
Thank you! I will restructure the folders this way then. 

Do you think this is the new train-test split authors propose in the paper? Were you able to reproduce the results of the paper for the Shanghai-Tech dataset?

**Comment by AbdulMoqeet** [comment]
I am not sure. I had to do reverse engineering to make this code work. So, by tracing the errors and codes, I came to that directory structure. 

I never meant to reproduce the quantitative results. However, I check some of qualitative results, there were positive results that ensure that code is working fine. I had to use this code for some other industrial application (for experimental purpose) that I am working on.

**Comment by abhishekaich27** [comment]
Alright. I have emailed the authors regarding this dataset's training/testing split and one of the authors has replied to get back to me in a while. I will update here if I get anything concrete.

Thank you again for your kind help.

**Comment by abhishekaich27** [comment]
@AbdulMoqeet The author of the repo confirmed that the folder structure you have is correct.

**Comment by AbdulMoqeet** [comment]
@abhishekaich27 Thanks a lot for the confirmation.

**Comment by BenedictGreen** [comment]
@AbdulMoqeet Hi, AbdulMoqeet. Thanks a lot for your conversation, my 'train.py' code is already running. Have you solved the problem of how to test the model?

**Comment by zugexiaodui** [comment]
Same question

**Comment by accountyangaaa** [comment]
@AbdulMoqeet Dear AbdulMoqeet, I would like to ask a question about train.py. When I ran it , this line of the code(
main(k_shots, num_tasks, adam_betas, gen_lr, dis_lr, total_epochs, model_folder_path) will raise the error(TypeError: add(): argument 'other' (position 1) must be Tensor, not BCELoss). Do you know how to fix it? Thank you.
Can you share your environment requirement？Thank you.

**Comment by AbdulMoqeet** [comment]
@accountyangaaa  Could you please run with default arguments? I have also shared a working code above. Check my answer to @carolchenyx  Please share a screenshot.

**Comment by accountyangaaa** [comment]
@AbdulMoqeet Thanks a lot for your reply.I just ran the working code above.There is another problem.Do you know how to fix it? Thank you.
The screenshot is as follows.
![image](https://user-images.githubusercontent.com/56595279/142824356-368ea4ea-adf0-4d31-8b43-634650b1af81.png)

**Comment by accountyangaaa** [comment]
@AbdulMoqeet  Dear AbdulMoqeet, thanks a lot for your reply. I just ran the working code above. There is another error.  
RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 4.00 GiB total capacity; 3.19 GiB already allocated; 0 bytes free; 28.04 MiB cached)
Do you know how to fix it? Thank you.
![result](https://user-images.githubusercontent.com/56595279/142825374-f2f3d882-cc63-4725-97e0-7f9241251ed4.png)

**Comment by carolchenyx** [comment]
Hi, maybe you can try to change to a smaller batch size.

accountyangaaa ***@***.***> 于2021年11月22日周一 下午4:00写道：

**Comment by accountyangaaa** [comment]
@carolchenyx Thanks a lot for your reply. Can I see your dataset structure

**Comment by accountyangaaa** [comment]
@carolchenyx Hi，below is the structure I have. Is this correct?
![res](https://user-images.githubusercontent.com/56595279/142986750-a9b37dec-3795-4f4c-b441-b9fe1f37a64e.png)

**Comment by zyzhang1998** [comment]
@AbdulMoqeet @carolchenyx  Hello, I see that you fix some bugs in original code. Especially, "load the previous model after gen_grads", I think it's right for MAML, and could you tell me how the model parameters update in the function "meta_update_model"? Thanks!

**Comment by carolchenyx** [comment]
> @carolchenyx Hi，below is the structure I have. Is this correct? ![res](https://user-images.githubusercontent.com/56595279/142986750-a9b37dec-3795-4f4c-b441-b9fe1f37a64e.png)

Hi, I think it's correct.

**Comment by dekathomas** [comment]
Hello @AbdulMoqeet @carolchenyx, where do you know the version list of the dependencies? Have you got information to test the trained model? Thank you

**Comment by AbdulMoqeet** [comment]
@dekathomas I did by trial & error. 

For testing, I made changes in the given code by following the paper. You can modify the train code accordingly.  I tested on my private dataset at that time and, the results were unsatisfactory.

**Comment by dekathomas** [comment]
Can you share to me the testing code you have made?

**Comment by AbdulMoqeet** [comment]
Sorry, I am not allowed to do so :-(

**Comment by dekathomas** [comment]
Owh oke, no problem

**Comment by lzyuan168** [comment]
@AbdulMoqeet Hi are you able to provide a skeleton code for the test.py file without the sensitive information. Thanks

**Comment by AbdulMoqeet** [comment]
@lzyuan168 Hi, I am sorry, I do not have access to those files anymore. 

As it's been long time so I do not even remember about them. If I remember correctly, I used train file/conditions to set conditions in  test file

**Comment by lzyuan168** [comment]
@AbdulMoqeet alright thank you
